"""create_outbox_events_table

Revision ID: 2838c57dcc77
Revises: 6c6aea5c9814
Create Date: 2026-09-10 00:49:46.133565

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from app.models.order import GUID


# revision identifiers, used by Alembic.
revision: str = "2838c57dcc77"
down_revision: str | Sequence[str] | None = "6c6aea5c9814"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outbox_events_aggregate_id"), ["aggregate_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_events_aggregate_type"), ["aggregate_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_events_event_type"), ["event_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_events_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbox_events_status"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_aggregate_type"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_aggregate_id"))

    op.drop_table("outbox_events")
    # ### end Alembic commands ###
