"""add_encrypted_nid_number_to_users

Revision ID: 6c6aea5c9814
Revises: 432a46573144
Create Date: 2026-09-09 21:02:36.312514

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import app.core.encryption


# revision identifiers, used by Alembic.
revision: str = "6c6aea5c9814"
down_revision: str | Sequence[str] | None = "432a46573144"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nid_number", app.core.encryption.EncryptedString(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("nid_number")

    # ### end Alembic commands ###
