"""create_double_entry_ledger_tables

Revision ID: 8bbc80ff6f79
Revises: b2c3d4e5f6a7
Create Date: 2026-09-11 07:27:27.387128

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8bbc80ff6f79"
down_revision: str | Sequence[str] | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.UUID(), nullable=False, comment="Monotonically increasing UUIDv7 identifier"),
        sa.Column(
            "reference_id",
            sa.String(length=128),
            nullable=False,
            comment="Unique idempotency / business reference identifier",
        ),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=False,
            comment="Audit rationale describing the monetary transfer",
        ),
        sa.Column(
            "posted_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when transaction was committed",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_journal_entries_reference_id"), ["reference_id"], unique=True)

    op.create_table(
        "ledger_accounts",
        sa.Column("id", sa.UUID(), nullable=False, comment="Monotonically increasing UUIDv7 identifier"),
        sa.Column(
            "account_number", sa.String(length=64), nullable=False, comment="Unique business-facing account number"
        ),
        sa.Column("name", sa.String(length=128), nullable=False, comment="Human-readable ledger account title"),
        sa.Column(
            "account_type",
            sa.Enum(
                "ASSET", "LIABILITY", "EQUITY", "REVENUE", "EXPENSE", name="accounttype", native_enum=False, length=20
            ),
            nullable=False,
            comment="Account type determining normal balance calculation",
        ),
        sa.Column("currency", sa.String(length=3), nullable=False, comment="ISO-4217 3-letter currency code"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Flag indicating if account accepts new postings"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when ledger account was created",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ledger_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ledger_accounts_account_number"), ["account_number"], unique=True)

    op.create_table(
        "journal_postings",
        sa.Column("id", sa.UUID(), nullable=False, comment="Monotonically increasing UUIDv7 identifier"),
        sa.Column("journal_entry_id", sa.UUID(), nullable=False, comment="Parent journal entry header ID"),
        sa.Column("account_id", sa.UUID(), nullable=False, comment="Target ledger account ID for this leg"),
        sa.Column(
            "amount",
            sa.Numeric(precision=18, scale=4),
            nullable=False,
            comment="Positive monetary quantity with 4 decimal places (Never float!)",
        ),
        sa.Column("direction", sa.String(length=6), nullable=False, comment="Movement direction: DEBIT or CREDIT"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="Timestamp when posting leg was inserted"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["ledger_accounts.id"],
        ),
        sa.ForeignKeyConstraint(["journal_entry_id"], ["journal_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("journal_postings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_journal_postings_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_journal_postings_journal_entry_id"), ["journal_entry_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journal_postings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_journal_postings_journal_entry_id"))
        batch_op.drop_index(batch_op.f("ix_journal_postings_account_id"))

    op.drop_table("journal_postings")
    with op.batch_alter_table("ledger_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ledger_accounts_account_number"))

    op.drop_table("ledger_accounts")
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_journal_entries_reference_id"))

    op.drop_table("journal_entries")
    # ### end Alembic commands ###
