"""add_permissions_bitmask_to_users

Revision ID: 9fcf16ef83c7
Revises: 35cee247200a
Create Date: 2026-09-09 17:27:12.760616

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fcf16ef83c7"
down_revision: str | Sequence[str] | None = "35cee247200a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("permissions", sa.Integer(), server_default="3", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("permissions")

    # ### end Alembic commands ###
