"""create_catalog_items_with_advanced_indices

Revision ID: d95d635922be
Revises: 2838c57dcc77
Create Date: 2026-09-10 11:55:15.780566

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd95d635922be'
down_revision: str | Sequence[str] | None = '2838c57dcc77'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.create_index('ix_catalog_barcode_hash', ['barcode'], unique=False, postgresql_using='hash')
        batch_op.create_index('ix_catalog_category_price', ['category', 'price'], unique=False)
        batch_op.create_index('ix_catalog_created_at_brin', ['created_at'], unique=False, postgresql_using='brin')
        batch_op.create_index(batch_op.f('ix_catalog_items_sku'), ['sku'], unique=True)
        batch_op.create_index('ix_catalog_metadata_gin', ['metadata_json'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_catalog_tags_gin', ['tags'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_tags_gin', postgresql_using='gin')
        batch_op.drop_index('ix_catalog_metadata_gin', postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_catalog_items_sku'))
        batch_op.drop_index('ix_catalog_created_at_brin', postgresql_using='brin')
        batch_op.drop_index('ix_catalog_category_price')
        batch_op.drop_index('ix_catalog_barcode_hash', postgresql_using='hash')

    op.drop_table('catalog_items')
    # ### end Alembic commands ###
